### ISSUE TITLE
64x48 OLED Adafruit_SSD1306 

### ISSUE THREAD

**Issue by phototobi** [thedarkman/ESP8266-Climate-Display-PubSub#1]
Hallo, dein Climate Display ist echt spitze. Ich habe aber ein Problem mit verschobener Darstellung, was nach etwas googlei wohl an dem Adafruit_SSD1306 und deren fehlende Unterstützung für das 64x48 shield liegt. Welche geforkte Version hast Du verwendet? Habe gelesen das Manche es damit hinbekommen haben. Nur wenn ich die Adafruit_SSD1306.h sowie .cpp und libary.properties austausche beschwert er sich beim compilieren mit: Error reading file (/Users/xxxxxxx/Documents/Arduino/libraries/Adafruit_SSD1306/library.properties:8): Invalid line format, should be 'key=value'

Fehler beim Kompilieren für das Board LOLIN(WEMOS) D1 R2 & mini.
Ungültige Bibliothek /Users/xxxxxxx/Documents/Arduino/libraries/Adafruit_SSD1306 in Missing 'version' from library gefunden

Wäre echt für einen Link dankbar. Oder sind die Shields echt so verschieden? Habe das Oled Shield und nicht das V1,1,0 shield.

Gruß

Tobias

**Comment by thedarkman** [comment]
Hi Tobias,

habe eben geschaut und die geforkte Version in der Readme angepasst. Es ist wohl diese hier:
https://github.com/mcauser/Adafruit_SSD1306/tree/esp8266-64x48

Damit geht es bei mir auf jeden Fall gut.
